# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "io.mattmoor.cloudevents.golang.functions"
version = "0.0.0"
name = "CloudEvent Golang Function Framework"
homepage = "https://github.com/mattmoor/cloudevent-go-fn"

# Stacks that the buildpack will work with
[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.buildpacks.samples.stacks.bionic"
